"""ai config: family_ai_config table

Revision ID: 30776978742d
Revises: f500d39dfa90
Create Date: 2026-06-28 22:00:37.641332

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '30776978742d'
down_revision: str | Sequence[str] | None = 'f500d39dfa90'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('family_ai_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('base_url', sa.String(length=255), nullable=True),
    sa.Column('api_key_encrypted', sa.String(length=500), nullable=True),
    sa.Column('monthly_quota', sa.Integer(), nullable=False),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_family_ai_config_family_id'), 'family_ai_config', ['family_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_family_ai_config_family_id'), table_name='family_ai_config')
    op.drop_table('family_ai_config')
    # ### end Alembic commands ###
