"""lesson conversation threading

Revision ID: 3c29534f459b
Revises: 7eed4f40a009
Create Date: 2026-06-29 12:12:57.856278

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3c29534f459b'
down_revision: str | Sequence[str] | None = '7eed4f40a009'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.add_column('lessons', sa.Column('root_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_lessons_root_id'), 'lessons', ['root_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lessons_root_id'), table_name='lessons')
    op.drop_column('lessons', 'root_id')
    op.drop_column('lessons', 'parent_id')
    # ### end Alembic commands ###
