"""child avatar_image_url

Revision ID: 7005ca28f0c3
Revises: 9ba3ea142d38
Create Date: 2026-06-30 17:26:17.096079

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7005ca28f0c3'
down_revision: str | Sequence[str] | None = '9ba3ea142d38'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('children', sa.Column('avatar_image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('children', 'avatar_image_url')
    # ### end Alembic commands ###
