"""lesson follow_ups column

Revision ID: 7eed4f40a009
Revises: c14d2e92bf0d
Create Date: 2026-06-29 10:27:31.078747

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7eed4f40a009'
down_revision: str | Sequence[str] | None = 'c14d2e92bf0d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('follow_ups', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'follow_ups')
    # ### end Alembic commands ###
