"""image generation config + lesson image_url

Revision ID: 9ba3ea142d38
Revises: e0162ca6164c
Create Date: 2026-06-30 07:47:57.571805

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9ba3ea142d38'
down_revision: str | Sequence[str] | None = 'e0162ca6164c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('family_ai_config', sa.Column('image_provider', sa.String(length=20), nullable=False, server_default='none'))
    op.add_column('family_ai_config', sa.Column('image_model', sa.String(length=120), nullable=True))
    op.add_column('family_ai_config', sa.Column('image_base_url', sa.String(length=255), nullable=True))
    op.add_column('family_ai_config', sa.Column('image_api_key_encrypted', sa.String(length=500), nullable=True))
    op.add_column('family_ai_config', sa.Column('image_enabled', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('lessons', sa.Column('image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'image_url')
    op.drop_column('family_ai_config', 'image_enabled')
    op.drop_column('family_ai_config', 'image_api_key_encrypted')
    op.drop_column('family_ai_config', 'image_base_url')
    op.drop_column('family_ai_config', 'image_model')
    op.drop_column('family_ai_config', 'image_provider')
    # ### end Alembic commands ###
