"""user recovery_code_hash

Revision ID: ad23d09d1b34
Revises: 7005ca28f0c3
Create Date: 2026-07-05 23:34:24.051270

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ad23d09d1b34'
down_revision: str | Sequence[str] | None = '7005ca28f0c3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('recovery_code_hash', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'recovery_code_hash')
    # ### end Alembic commands ###
