"""child avatar column

Revision ID: c14d2e92bf0d
Revises: 90ff6eb610f4
Create Date: 2026-06-29 01:20:41.737263

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c14d2e92bf0d'
down_revision: str | Sequence[str] | None = '90ff6eb610f4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("children", sa.Column("avatar", sa.String(length=40), nullable=False, server_default="fox"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('children', 'avatar')
    # ### end Alembic commands ###
