"""knowledge node root_lesson_id

Revision ID: e0162ca6164c
Revises: 3c29534f459b
Create Date: 2026-06-29 13:06:01.490723

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e0162ca6164c'
down_revision: str | Sequence[str] | None = '3c29534f459b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_nodes', sa.Column('root_lesson_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_nodes', 'root_lesson_id')
    # ### end Alembic commands ###
