"""nucleo: lessons and knowledge_nodes

Revision ID: f500d39dfa90
Revises: b3a563ae9701
Create Date: 2026-06-28 20:47:37.488658

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f500d39dfa90'
down_revision: str | Sequence[str] | None = 'b3a563ae9701'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('concept', sa.String(length=120), nullable=False),
    sa.Column('subject', sa.String(length=40), nullable=False),
    sa.Column('mastery', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_nodes_child_id'), 'knowledge_nodes', ['child_id'], unique=False)
    op.create_table('lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('curiosity', sa.String(length=300), nullable=False),
    sa.Column('subject', sa.String(length=40), nullable=False),
    sa.Column('concept', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('fun_fact', sa.Text(), nullable=False),
    sa.Column('quiz_question', sa.String(length=300), nullable=False),
    sa.Column('quiz_options', sa.JSON(), nullable=False),
    sa.Column('quiz_correct_index', sa.Integer(), nullable=False),
    sa.Column('quiz_explanation', sa.Text(), nullable=False),
    sa.Column('answered', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lessons_child_id'), 'lessons', ['child_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lessons_child_id'), table_name='lessons')
    op.drop_table('lessons')
    op.drop_index(op.f('ix_knowledge_nodes_child_id'), table_name='knowledge_nodes')
    op.drop_table('knowledge_nodes')
    # ### end Alembic commands ###
